; This file was auto-generated by drush make
core = 7.x
api = 2

projects[] = drupal
projects[] = views_bulk_operations
projects[] = admin_menu
projects[] = admin_views
projects[] = ctools
projects[] = ckeditor
projects[] = ckeditor_link
projects[] = colorbox
projects[] = devel
projects[] = display_cache

projects[] = editableviews

projects[] = entity

projects[] = entityreference

projects[] = field_formatter_settings

projects[] = field_multiple_limit

projects[] = filefield_sources

projects[] = globalredirect

projects[] = imagecache_actions

projects[] = imagecache_token

projects[] = imce

projects[] = jquery_update

projects[] = l10n_update

projects[] = less

projects[] = libraries

projects[] = linkchecker

projects[] = menu_editor

projects[] = metatag

projects[] = mollom

projects[] = multiupload_filefield_widget

projects[] = multiupload_imagefield_widget

projects[] = nodequeue

projects[] = path_breadcrumbs

projects[] = pathauto

projects[] = smtp

projects[] = token

projects[] = transliteration

projects[] = views

projects[] = webform

projects[] = xmlsitemap

; Themes
projects[] = bootstrap

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[less.php][download][type] = "file"
libraries[less.php][download][url] = "https://github.com/oyejorge/less.php/releases/download/v1.7.0.3/less.php_1.7.0.3.zip"
libraries[less.php][directory_name] = "less.php"
libraries[less.php][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.4.7/ckeditor_4.4.7_full.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "file"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

;Profiles
projects[smg][download][type] = "git"
projects[smg][download][url] = "https://github.com/Koreychenko/baseprofile"
projects[smg][download][branch] = "master"
projects[smg][type] = "profile"
